using MiniOrm.Mapping;
using MiniOrm.Query;
using Npgsql;

namespace MiniOrm.Migrations;

public sealed class GeneratedMigration
{
    public required string Name { get; init; }
    public required string UpSql { get; init; }
    public required string DownSql { get; init; }
    public bool HasChanges => !string.IsNullOrWhiteSpace(UpSql);
}

internal sealed class ColumnSchema
{
    public required string Name { get; init; }
    public required string DataType { get; init; }
    public bool IsNullable { get; init; }
    public bool IsIdentity { get; init; }
    public string? DefaultSql { get; init; }
}

internal sealed class TableSchema
{
    public required string Name { get; init; }
    public List<ColumnSchema> Columns { get; } = new();
    public List<string> PrimaryKey { get; } = new();
    public List<(string Column, string RefTable, string RefColumn)> ForeignKeys { get; } = new();
    public List<string> UniqueColumns { get; } = new();
}

public sealed class MigrationRunner
{
    private readonly MiniOrmContext _context;
    private const string HistoryTable = "__miniorm_migrations";

    public MigrationRunner(MiniOrmContext context) => _context = context;

    public GeneratedMigration Generate(string? name = null)
    {
        EnsureHistoryTable();
        var desired = BuildDesired();
        var actual = ReadActual();
        var (up, down) = Diff(desired, actual);
        return new GeneratedMigration
        {
            Name = name ?? $"auto_{DateTime.UtcNow:yyyyMMdd_HHmmss}",
            UpSql = up,
            DownSql = down
        };
    }

    public void ApplyPending()
    {
        var generated = Generate();
        if (!generated.HasChanges)
            return;

        using var tx = _context.Connection.BeginTransaction();
        try
        {
            using (var cmd = new NpgsqlCommand(generated.UpSql, _context.Connection))
            {
                cmd.Transaction = tx;
                cmd.ExecuteNonQuery();
            }
            InsertHistory(generated, tx);
            tx.Commit();
        }
        catch
        {
            tx.Rollback();
            throw;
        }
    }

    public void RollbackLast()
    {
        EnsureHistoryTable();
        using var select = new NpgsqlCommand(
            $"SELECT name, down_sql FROM {Q(HistoryTable)} ORDER BY id DESC LIMIT 1;",
            _context.Connection);
        using var reader = select.ExecuteReader();
        if (!reader.Read())
            throw new InvalidOperationException("Nema migracija za rollback.");

        var name = reader.GetString(0);
        var down = reader.GetString(1);
        reader.Close();

        if (!string.IsNullOrWhiteSpace(down))
        {
            using var downCmd = new NpgsqlCommand(down, _context.Connection);
            downCmd.ExecuteNonQuery();
        }

        using var delete = new NpgsqlCommand(
            $"DELETE FROM {Q(HistoryTable)} WHERE name = @n;",
            _context.Connection);
        delete.Parameters.AddWithValue("@n", name);
        delete.ExecuteNonQuery();
    }

    public IReadOnlyList<(int Id, string Name, DateTimeOffset AppliedAt)> History()
    {
        EnsureHistoryTable();
        using var cmd = new NpgsqlCommand(
            $"SELECT id, name, applied_at FROM {Q(HistoryTable)} ORDER BY id;",
            _context.Connection);
        var list = new List<(int, string, DateTimeOffset)>();
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
            list.Add((reader.GetInt32(0), reader.GetString(1), reader.GetFieldValue<DateTimeOffset>(2)));
        return list;
    }

    private void InsertHistory(GeneratedMigration migration, NpgsqlTransaction? tx = null)
    {
        using var cmd = new NpgsqlCommand(
            $"INSERT INTO {Q(HistoryTable)} (name, up_sql, down_sql) VALUES (@n, @u, @d);",
            _context.Connection);
        if (tx is not null)
            cmd.Transaction = tx;
        cmd.Parameters.AddWithValue("@n", migration.Name);
        cmd.Parameters.AddWithValue("@u", migration.UpSql);
        cmd.Parameters.AddWithValue("@d", migration.DownSql);
        cmd.ExecuteNonQuery();
    }

    private void EnsureHistoryTable()
    {
        using var cmd = new NpgsqlCommand($"""
            CREATE TABLE IF NOT EXISTS {Q(HistoryTable)} (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(200) NOT NULL UNIQUE,
                up_sql TEXT NOT NULL,
                down_sql TEXT NOT NULL,
                applied_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            );
            """, _context.Connection);
        cmd.ExecuteNonQuery();
    }

    private Dictionary<string, TableSchema> BuildDesired()
    {
        var tables = new Dictionary<string, TableSchema>(StringComparer.OrdinalIgnoreCase);
        foreach (var type in _context.EntityTypes)
        {
            var meta = MetadataCache.Get(type);
            var table = new TableSchema { Name = meta.TableName };
            foreach (var col in meta.Columns)
            {
                table.Columns.Add(new ColumnSchema
                {
                    Name = col.ColumnName,
                    DataType = col.PostgresType,
                    IsNullable = col.IsNullable,
                    IsIdentity = col.IsIdentity,
                    DefaultSql = col.DefaultSql
                });
                if (col.IsKey) table.PrimaryKey.Add(col.ColumnName);
                if (col.IsUnique) table.UniqueColumns.Add(col.ColumnName);
                if (col.ForeignTable is not null)
                    table.ForeignKeys.Add((col.ColumnName, col.ForeignTable, col.ForeignColumn ?? "id"));
            }
            tables[table.Name] = table;
        }
        return tables;
    }

    private Dictionary<string, TableSchema> ReadActual()
    {
        var tables = new Dictionary<string, TableSchema>(StringComparer.OrdinalIgnoreCase);

        using (var cmd = new NpgsqlCommand("""
            SELECT table_name, column_name, data_type, udt_name, is_nullable,
                   column_default, is_identity, character_maximum_length, numeric_precision, numeric_scale
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name <> @history
            ORDER BY table_name, ordinal_position;
            """, _context.Connection))
        {
            cmd.Parameters.AddWithValue("@history", HistoryTable);
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var tableName = reader.GetString(0);
                if (!tables.TryGetValue(tableName, out var table))
                {
                    table = new TableSchema { Name = tableName };
                    tables[tableName] = table;
                }

                var columnName = reader.GetString(1);
                var dataType = reader.GetString(2);
                var udt = reader.GetString(3);
                var maxLen = reader.IsDBNull(7) ? (int?)null : Convert.ToInt32(reader.GetValue(7));
                var prec = reader.IsDBNull(8) ? (int?)null : Convert.ToInt32(reader.GetValue(8));
                var scale = reader.IsDBNull(9) ? (int?)null : Convert.ToInt32(reader.GetValue(9));

                table.Columns.Add(new ColumnSchema
                {
                    Name = columnName,
                    DataType = NormalizeDbType(dataType, udt, maxLen, prec, scale),
                    IsNullable = reader.GetString(4) == "YES",
                    IsIdentity = reader.GetString(6) == "YES",
                    DefaultSql = reader.IsDBNull(5) ? null : reader.GetString(5)
                });
            }
        }

        using (var cmd = new NpgsqlCommand("""
            SELECT tc.table_name, kcu.column_name, tc.constraint_type
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
            WHERE tc.table_schema = 'public' AND tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE');
            """, _context.Connection))
        using (var reader = cmd.ExecuteReader())
        {
            while (reader.Read())
            {
                var tableName = reader.GetString(0);
                if (!tables.TryGetValue(tableName, out var table)) continue;
                var col = reader.GetString(1);
                if (reader.GetString(2) == "PRIMARY KEY")
                    table.PrimaryKey.Add(col);
                else
                    table.UniqueColumns.Add(col);
            }
        }

        using (var cmd = new NpgsqlCommand("""
            SELECT
                kcu.table_name,
                kcu.column_name,
                ccu.table_name AS foreign_table,
                ccu.column_name AS foreign_column
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
            JOIN information_schema.constraint_column_usage ccu
              ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
            WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public';
            """, _context.Connection))
        using (var reader = cmd.ExecuteReader())
        {
            while (reader.Read())
            {
                var tableName = reader.GetString(0);
                if (!tables.TryGetValue(tableName, out var table)) continue;
                table.ForeignKeys.Add((reader.GetString(1), reader.GetString(2), reader.GetString(3)));
            }
        }

        return tables;
    }

    private static (string Up, string Down) Diff(
        Dictionary<string, TableSchema> desired,
        Dictionary<string, TableSchema> actual)
    {
        var up = new List<string>();
        var down = new List<string>();

        foreach (var table in desired.Values)
        {
            if (!actual.TryGetValue(table.Name, out var existing))
            {
                up.Add(CreateTableSql(table));
                down.Insert(0, $"DROP TABLE IF EXISTS {Q(table.Name)} CASCADE;");
                continue;
            }

            foreach (var col in table.Columns)
            {
                var current = existing.Columns.FirstOrDefault(c => c.Name.Equals(col.Name, StringComparison.OrdinalIgnoreCase));
                if (current is null)
                {
                    up.Add($"ALTER TABLE {Q(table.Name)} ADD COLUMN {ColumnDefinition(col, table)};");
                    down.Insert(0, $"ALTER TABLE {Q(table.Name)} DROP COLUMN IF EXISTS {Q(col.Name)};");
                    continue;
                }

                if (!TypesCompatible(current.DataType, col.DataType))
                {
                    up.Add($"ALTER TABLE {Q(table.Name)} ALTER COLUMN {Q(col.Name)} TYPE {col.DataType} USING {Q(col.Name)}::{col.DataType};");
                    down.Insert(0, $"ALTER TABLE {Q(table.Name)} ALTER COLUMN {Q(col.Name)} TYPE {current.DataType};");
                }

                if (current.IsNullable != col.IsNullable)
                {
                    up.Add(col.IsNullable
                        ? $"ALTER TABLE {Q(table.Name)} ALTER COLUMN {Q(col.Name)} DROP NOT NULL;"
                        : $"ALTER TABLE {Q(table.Name)} ALTER COLUMN {Q(col.Name)} SET NOT NULL;");
                    down.Insert(0, current.IsNullable
                        ? $"ALTER TABLE {Q(table.Name)} ALTER COLUMN {Q(col.Name)} DROP NOT NULL;"
                        : $"ALTER TABLE {Q(table.Name)} ALTER COLUMN {Q(col.Name)} SET NOT NULL;");
                }
            }
        }

        return (string.Join("\n", up), string.Join("\n", down));
    }

    private static string CreateTableSql(TableSchema table)
    {
        var cols = table.Columns.Select(c => ColumnDefinition(c, table));
        var pk = table.PrimaryKey.Count > 0
            ? $", PRIMARY KEY ({string.Join(", ", table.PrimaryKey.Select(Q))})"
            : "";
        var uniques = table.UniqueColumns
            .Where(u => !table.PrimaryKey.Contains(u, StringComparer.OrdinalIgnoreCase))
            .Select(u => $", UNIQUE ({Q(u)})");
        var fks = table.ForeignKeys.Select(fk =>
            $", FOREIGN KEY ({Q(fk.Column)}) REFERENCES {Q(fk.RefTable)} ({Q(fk.RefColumn)})");
        return $"CREATE TABLE {Q(table.Name)} (\n  {string.Join(",\n  ", cols)}{pk}{string.Concat(uniques)}{string.Concat(fks)}\n);";
    }

    private static string ColumnDefinition(ColumnSchema col, TableSchema table)
    {
        var identity = col.IsIdentity ? " GENERATED BY DEFAULT AS IDENTITY" : "";
        var nullability = col.IsNullable ? "" : " NOT NULL";
        var def = string.IsNullOrWhiteSpace(col.DefaultSql) ? "" : $" DEFAULT {col.DefaultSql}";
        return $"{Q(col.Name)} {col.DataType}{identity}{nullability}{def}";
    }

    private static bool TypesCompatible(string dbType, string modelType)
    {
        static string Norm(string t) => t.ToUpperInvariant()
            .Replace("TIMESTAMP WITH TIME ZONE", "TIMESTAMPTZ")
            .Replace("TIMESTAMP WITHOUT TIME ZONE", "TIMESTAMP")
            .Replace("CHARACTER VARYING", "VARCHAR")
            .Replace("DOUBLE PRECISION", "FLOAT")
            .Replace("NUMERIC", "DECIMAL")
            .Replace("INTEGER", "INT")
            .Replace(" ", "");
        return Norm(dbType) == Norm(modelType) ||
               Norm(dbType).StartsWith(Norm(modelType), StringComparison.Ordinal) ||
               Norm(modelType).StartsWith(Norm(dbType), StringComparison.Ordinal);
    }

    private static string NormalizeDbType(string dataType, string udt, int? maxLen, int? prec, int? scale)
    {
        var t = dataType.ToLowerInvariant();
        return t switch
        {
            "integer" => "INTEGER",
            "bigint" => "BIGINT",
            "smallint" => "SMALLINT",
            "real" => "REAL",
            "double precision" => "DOUBLE PRECISION",
            "numeric" => prec is > 0 ? $"DECIMAL({prec},{scale ?? 0})" : "DECIMAL",
            "character varying" => maxLen is > 0 ? $"VARCHAR({maxLen})" : "VARCHAR",
            "character" => maxLen is > 0 ? $"CHAR({maxLen})" : "CHAR",
            "text" => "TEXT",
            "timestamp with time zone" => "TIMESTAMP WITH TIME ZONE",
            "timestamp without time zone" => "TIMESTAMP WITHOUT TIME ZONE",
            "boolean" => "BOOLEAN",
            "uuid" => "UUID",
            _ => udt.ToUpperInvariant()
        };
    }

    private static string Q(string ident) => WhereTranslator.Quote(ident);
}
